[project]
name = "qgis-mcp-fields"
version = "0.2.0"
description = "Enhanced QGIS Model Context Protocol integration with feature attribute capabilities"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.3.0",
]
